# Generated by Django 3.0.5 on 2020-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('teamName', models.CharField(default='hello', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'teams',
            },
        ),
    ]
