# Generated by Django 3.0.5 on 2020-05-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_team_1', models.IntegerField()),
                ('overs_team_1', models.FloatField()),
                ('wickets_team_1', models.IntegerField()),
                ('team_name_1', models.ForeignKey(db_column='team_name_1', on_delete=django.db.models.deletion.CASCADE, to='rcl.Teams')),
            ],
        ),
    ]
