# Generated by Django 3.0.5 on 2020-05-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcl', '0003_auto_20200506_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField()),
                ('won', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('tie', models.IntegerField()),
                ('points', models.IntegerField()),
                ('net_runrate', models.FloatField()),
                ('team_name', models.ForeignKey(db_column='team_name', default='team', on_delete=django.db.models.deletion.CASCADE, to='rcl.Teams')),
            ],
        ),
    ]
