# Generated by Django 3.0.5 on 2020-05-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcl', '0004_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name_plural': 'Points_table'},
        ),
        migrations.AlterField(
            model_name='points',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='net_runrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='points',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='tie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='points',
            table='Points',
        ),
    ]
