# Generated by Django 3.0.5 on 2020-05-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcl', '0005_auto_20200506_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='team_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
