# Generated by Django 3.0.5 on 2020-05-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcl', '0006_points_team_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='user_desc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
