# Generated by Django 3.0.5 on 2020-05-09 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcl', '0007_auto_20200509_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='team_flag',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_flag', models.ImageField(blank=True, null=True, upload_to='')),
                ('team_2_flag', models.ImageField(blank=True, null=True, upload_to='')),
                ('venue', models.CharField(default='Cape Town', max_length=10)),
                ('team_1', models.ForeignKey(db_column='team_1', default='team', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='rcl.Teams')),
            ],
            options={
                'verbose_name_plural': 'Fixtures',
            },
        ),
    ]
