# Generated by Django 3.0.5 on 2020-05-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcl', '0008_auto_20200509_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='team_2',
            field=models.ForeignKey(db_column='team_2', default='team', max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='rcl.Teams'),
        ),
    ]
