# Generated by Django 3.0.5 on 2020-05-09 05:36

from django.db import migrations, models
import rcl.models


class Migration(migrations.Migration):

    dependencies = [
        ('rcl', '0009_fixture_team_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='team_1_flag',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=rcl.models.Teams),
        ),
    ]
