# Generated by Django 3.0.5 on 2020-05-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcl', '0010_auto_20200509_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='team_1_flag',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
